### ISSUE TITLE
Why did you guys decide to use Kotlin?

### ISSUE THREAD

**Issue by Starlight220** [FRC5190/2020CompetitionSeason#70]
We (6738) currently use Java, and I am thinking of moving to Kotlin for next year. What are the (dis)advantages of Kotlin in comparison to Java in an FRC context?

And what photoelectric sensors did you use (and where in the code do you use them)?

**Comment by prateekma** [comment]
We tried out Kotlin in 2018 and used it ever since simply because we like it. Our units library has no overhead and this is only possible in Kotlin due to inline classes. 

We're using Automation Direct QMRB-0N-0A photoelectric sensors and they're the AnalogInputs in the Intake class.

**Comment by Starlight220** [comment]
And other than units (that there isn't much need for in java), what convenience or other advantage does Kotlin have in an FRC context?

**Comment by prateekma** [comment]
It's less verbose, we make heavy use of extension functions and we simply like it more than Java. It might not be a compelling reason for you, but it is for us.

**Comment by Starlight220** [comment]
Ok, I will think about it more, thanks for the food for thought!
